cschleiden/go-workflows

README.md
internal/converter/converter.go
internal/workflow/activity.go
internal/workflow/executor_test.go
internal/workflow/retries.go
internal/workflow/subworkflow.go
pkg/workflow/workflow.go
samples/cancellation/cancellation.go
samples/complex-parameters/complex-parameters.go
samples/concurrent/concurrent.go
samples/errors/errors.go
samples/retries/retries.go
samples/scale/workflow.go
samples/signal/signal.go
samples/simple-split-worker/workflow.go
samples/simple/simple.go
samples/subworkflow/subworkflow.go

Activity & sub-workflow retries

---

backend/redis/workflow.go

Might change how pending events are stored and then just have a pointer in the sorted set to that data. But for now just ignore instance that are already completed or don't exist.

Ignore future event when instance already ended or not found

---

internal/sync/coroutine.go
internal/tester/tester_test.go
internal/workflow/executor.go
internal/workflow/executor_test.go
internal/workflow/workflow.go

Transition workflow to an error state when encountering a panic or error

---

backend/test/e2e.go
internal/activity/executor.go
internal/activity/executor_test.go
internal/args/args.go
internal/args/args_test.go
internal/workflow/executor_test.go

Fixes this for workflows and activities. 
Closes: https://github.com/cschleiden/go-workflows/issues/61

Validate input counts for workflows and activities

---

analyzer/analyzer.go
analyzer/testdata/src/p/p.go

Add remaining checks to analyzer

---

README.md

this pull-request only makes a minor update to the readme, adding link to the part2 blog post by @cschleiden.

added a link to the part2 blog-post.

---

diag/backend.go

Always serialize instance state for diag UI

---

backend/mysql/diagnostics.go
backend/redis/workflow.go
backend/test/backendtest.go

Also adds mysql diag backend modeled after the sqlite one.
Closes #76

Store completed_at for redis backend

---

README.md

Document signals

---

internal/sync/channel.go

Remove the Converter reference from the channel for now

Remove converter reference on channel impl

---

.vscode/settings.json
backend/mysql/events.go
backend/mysql/mysql.go
backend/mysql/mysql_test.go
backend/mysql/schema.sql
backend/redis/events.go
backend/redis/keys.go
backend/redis/queue.go
backend/redis/redis.go
backend/redis/redis_test.go
backend/redis/workflow.go
backend/sqlite/events.go
backend/sqlite/schema.sql
backend/sqlite/sqlite.go
backend/sqlite/sqlite_test.go
backend/test/backend.go
backend/test/backendtest.go
backend/test/bench.go
backend/test/e2e.go
internal/sync/scheduler_test.go
internal/workflow/executor_test.go

Cleanup future pending events when cancelling timers 

---

backend/test/e2e.go
internal/workflow/executor.go

Set schedule event ids to 0 for workflow started events

---

backend/redis/events.go
backend/test/e2e.go
internal/command/sideeffect.go
internal/workflow/executor.go
workflow/sideeffect.go

Ensure errors encountered during replay can be saved & Fix SideEffect determinism check

---

README.md
backend/mysql/mysql.go
backend/redis/workflow.go
backend/sqlite/sqlite.go
backend/test/e2e.go
internal/command/signal.go
internal/history/grouping.go
internal/history/grouping_test.go
internal/history/history.go
internal/history/serialization.go
internal/history/signal_workflow.go
internal/workflow/executor.go
samples/runner.go
samples/signal-subworkflow/subworkflow-signal.go
workflow/signal.go

Signal other workflows

---

internal/workflow/executor_test.go
workflow/timer.go

Support multiple timer cancellations

---

internal/workflow/executor.go
internal/workflow/executor_test.go
internal/workflowstate/workflowstate.go
internal/workflowstate/workflowstate_test.go
samples/timer/timer.go
workflow/sideeffect.go

In the future this will change to be recoverable, but for now I want to make it explicit

Panic when completing workflow with pending futures

---

tester/tester.go
tester/tester_subworkflow_test.go
tester/tester_test.go

Fix an issue where signal from within workflows weren't delivered in unit tested workflows

Fix signaling in tester workflows

---

.github/workflows/go.yml
tester/tester.go

Only cancel timers for workflow instances.

Only cancel workflow timers

---

internal/workflow/executor.go

After the changes in #151, the executor no longer needs this sentinel field that indicates whether a `WorkflowExecutionStarted` event was already seen or not.
This fully completes the reversion of the changes from #145.

Remove unused `wfStartedEventSeen` field

---

.github/workflows/go.yml

Splits the e2e tests into separate jobs
Closes: #110

Run tests in parallel

---

internal/fn/fn.go
internal/fn/fn_test.go
workflow/activity.go
workflow/activity_test.go
workflow/subworkflow.go
workflow/subworkflow_test.go

Check return types when scheduling activities and sub workflows

---

tester/tester.go
tester/tester_activity_test.go
tester/tester_timers_test.go

Schedule wall-clock timers during activities

---

go.mod
go.sum
internal/logger/logger.go

Provide log output that's a bit easier to parse.

Humanize log output

---

README.md
activitytester/activitytester.go
activitytester/activitytester_test.go
tester/tester_activity_test.go

Support testing activities that make use of the activity context.

Support testing activities

---

analyzer/analyzer.go
analyzer/testdata/src/p/p.go

- Add failing test
- Fall back to default import name

Use default import name from analyzer

---

backend/mysql/mysql.go
backend/sqlite/sqlite.go

Turns out this was an actual bug in the mysql backend. Also updated sqlite for consistency. 
Closes: https://github.com/cschleiden/go-workflows/issues/232

Fix continueAsNew race condition for sql backends

---

samples/activity-registration/activity-registration.go
samples/cancellation/cancellation.go
samples/complex-parameters/complex-parameters.go
samples/concurrent/concurrent.go
samples/signal/signal.go

Follow up for #222. For some reason my local build didn't show those.

Ensure log values have keys in samples

---

backend/redis/expire_test.go

Improve flaky redis unit tests

---

samples/concurrent/concurrent.go

Multiple ways to fix this, went with spawning a couple `workflow.Go` routines for now.
Closes: #236

Run activities in parallel for `concurrent` sample

---

backend/test/e2e.go
internal/worker/workflow.go
internal/workflow/cache.go
internal/workflow/cache/cache.go

Explicitly evict finished workflow instances from cache

---

backend/mysql/stats.go
backend/redis/stats.go
backend/sqlite/stats.go
backend/stats.go
backend/test/e2e_stats.go

Closes: https://github.com/cschleiden/go-workflows/issues/134

Add pending workflow tasks metric to stats interface

---

backend/monoprocess/monoprocess.go
backend/redis/events_future.go
backend/redis/instance.go
backend/redis/redis.go
client/client.go
internal/args/args_test.go
internal/workflow/cache/cache_test.go
internal/workflow/executor_test.go
internal/workflow/registry_test.go
internal/workflowerrors/stack.go
internal/workflowtracer/tracer.go
samples/tracing/workflow.go
worker/worker.go

Rang `golangci-lint` and fixed various smaller issues

Fix some linting errors

---

backend/redis/diagnostics.go
backend/redis/instance.go
backend/redis/redis.go
backend/redis/scripts/create_workflow_instance.lua
client/client.go

This pull request refactors the workflow instance creation process and improves the logging output. The changes include:
- Using the correct key for checking whether an instance exists
- Moving the instance creation to a Lua script
- Including the workflow name in the log output
These changes optimize the workflow instance creation and provide more detailed and informative log messages.
Fixes #291

Refactor workflow instance creation

---

.vscode/launch.json
client/client.go
client/client_test.go
samples/workflow-registration/workflow.go
samples/workflow-registration/workflow_registration.go
samples/workflow-registration/workflow_registration_test.go
workflow/subworkflow.go
workflow/subworkflow_test.go

With this change you can start workflow instances by name and also execute sub-workflows by name.

Execute workflows by (custom) name

---

internal/workflowstate/replaylogger.go
internal/workflowstate/replaylogger_test.go

Keep ReplayHandler when using With or WithGroup

---

internal/workflow/executor.go

With this change, when there are pending futures at the end of a workflow, we'll transition that workflow to an error state. If the workflow is executed during a `go test` test run, it will panic to make it easier to identify problems during development.

Do not panic at runtime for pending futures

---

internal/worker/workflow.go
internal/workflow/executor.go

Remove remaining panics

---

backend/redis/expire_test.go
backend/redis/options.go
backend/redis/workflow.go

Support custom expiration for continue-as-new workflows

---

backend/redis/delete.go
backend/redis/diagnostics.go
backend/redis/events.go
backend/redis/events_future.go
backend/redis/expire.go
backend/redis/instance.go
backend/redis/keys.go
backend/redis/keys_test.go
backend/redis/options.go
backend/redis/queue.go
backend/redis/queue_test.go
backend/redis/redis.go
backend/redis/redis_test.go
backend/redis/signal.go
backend/redis/stats.go
backend/redis/workflow.go
docs/source/includes/_backends.md

Support a custom key prefix for the redis backend

Support key prefix for redis backend

---

backend/redis/instance.go
backend/redis/keys.go
backend/redis/scripts/complete_workflow_task.lua
backend/redis/workflow.go

Remove `historyID` and its usages.

Remove historyId

---

internal/sync/channel.go
internal/sync/channel_test.go
internal/sync/context.go
workflow/channel.go
workflow/context.go

Context and channel improvements

---

internal/worker/workflow.go

Executors are cached and can process multiple workflow tasks. We must not include the task id in the logger that's persisted there.

Fix incorrect tasklogger

---

workflow/retries.go

Two changes:
- No need to wait first and _then_ decide that we've reached maximum # of retries, exit sooner
- Same vein, no need to first want and then check that we've exceeded that max time to wait

Stop subworkflow/activity retries sooner

---

backend/mysql/diagnostics.go
backend/redis/diagnostics.go
backend/redis/instance.go
backend/test/e2e.go
backend/test/e2e_diag.go

Closes: Pagination not working in diag UI #343

Fix mysql pagination

---

client/client.go

Closes: https://github.com/cschleiden/go-workflows/issues/345

Expose GetWorkflowInstanceState from client

---

backend/backend.go
backend/mock_Backend.go
backend/mysql/mysql.go
backend/redis/instance.go
backend/removal.go
backend/sqlite/sqlite.go
backend/test/e2e.go
backend/test/e2e_removal.go
client/client.go
docs/source/includes/_guide.md

Contributes to: https://github.com/cschleiden/go-workflows/issues/28

Support removing workflow instances

---

backend/backend.go
backend/features.go
backend/mock_Backend.go
backend/mysql/mysql.go
backend/redis/redis.go
backend/removal.go
backend/sqlite/sqlite.go
backend/test/e2e_removal.go
client/expiration.go
internal/workflows/expiration.go
worker/worker.go

Support auto-expiration for all backends

---

backend/mysql/mysql.go
backend/options.go
backend/redis/instance.go
backend/redis/workflow.go
backend/sqlite/sqlite.go
backend/test/e2e.go
backend/test/e2e_activity.go
backend/test/e2e_continueasnew.go
backend/test/e2e_diag.go
backend/test/e2e_queues.go
backend/test/e2e_stats.go
backend/test/e2e_timer.go
internal/command/continueasnew.go

Support removing ContinuedAsNew instances immediately
