cschleiden/go-workflows

backend/backend.go, backend/mock_Backend.go, backend/mysql/mysql.go, backend/sqlite/schema.sql, backend/sqlite/sqlite.go, client/client.go, client/client_test.go, samples/simple/simple.go
`GetWorkflowResult` polls the backend for the history of a workflow, checks
for events indicating workflow completion, and then returns the results
from the event's attributes.
If the workflow has not yet completed, it will wait and then poll again until
the given timeout is reached.
In the future, this should be optimized to only fetch history events of interest,
but for now it just pulls down the full history.
=> Add GetWorkflowResult to client

backend/backend.go, backend/mysql/events.go, backend/mysql/mysql.go, backend/mysql/schema.sql, backend/redis/redis.go, backend/redis/taskqueue/queue.go, backend/redis/taskqueue/queue_test.go, backend/sqlite/events.go, backend/sqlite/schema.sql, backend/sqlite/sqlite.go, backend/test/backendtest.go, client/client.go, client/client_test.go, internal/command/command.go, internal/core/instance.go, internal/history/history.go, internal/history/serialization_test.go, internal/tester/tester.go, internal/worker/activity.go, internal/worker/workflow.go, internal/workflow/executor.go, internal/workflow/executor_test.go, internal/workflowstate/workflowstate.go, samples/subworkflow/subworkflow.go
This is in preparation for making the continuation logic less dependent on the backend and to allow the executor to pull in the history.
This will also enable some cleanup in the mysql and sqlite backends, but that will be a follow up change.
=> Add executor generated sequence ids

backend/backend.go, backend/mock_Backend.go, backend/mysql/mysql.go, backend/redis/instance.go, backend/redis/redis.go, backend/redis/workflow.go, backend/sqlite/events.go, backend/sqlite/sqlite.go, backend/test/backendtest.go, client/client.go, internal/task/workflow.go, internal/tester/tester.go, internal/worker/workflow.go, internal/workflow/cache.go, internal/workflow/cache_test.go, internal/workflow/executor.go, internal/workflow/executor_test.go, internal/workflow/workflow.go, samples/scale/starter/main.go, samples/scale/worker/main.go, samples/simple/simple.go, samples/subworkflow/subworkflow.go
This replaces continuation tasks with an explicit call to get the history when required.
Closes: #37
=> Remove continuation task

backend/mysql/mysql_test.go, backend/redis/redis_test.go, backend/sqlite/sqlite_test.go, backend/test/e2e.go, internal/worker/activity.go, internal/worker/workflow.go, internal/workflow/executor.go, samples/simple/simple.go, samples/subworkflow/subworkflow.go, samples/timer/timer.go, worker/worker.go
This PR adds some simple E2E tests for the different backends. The goal is to do some closed-box testing and use the APIs like a consumer would. 
This is a start, planning to add more scenarios -- especially ones that don't follow the "happy path" and to make sure that they don't take down the worker or client.
=> Add some simple E2E tests

internal/command/command.go, internal/sync/coroutine.go, internal/sync/future.go, internal/workflow/executor.go, internal/workflow/executor_test.go
This PR updates some of the error messages returned when a workflow execution shows different behavior from the event in the history. 
It also removes some unnecessary calls to remove (pending) commands from the workflow state.
=> Improve error messages when workflow replays yield different commands

analyzer/analyzer.go, analyzer/testdata/src/p/p.go
Closes: Linter always reports `time.Now` usage #65
=> Ensure linter only analyzes statements in top-level workflow functions

backend/mysql/mysql.go, backend/redis/instance.go, backend/sqlite/sqlite.go, backend/test/backendtest.go, backend/test/e2e.go
Previously when a workflow was canceled the backend was responsible for finding all sub-workflows and added a cancellation event to their pending event queues. 
This removes this behavior and instead relies on the normal context cancellation logic for propagating cancellation. The workflow that's canceled receives a `..._CANCELED` event. This will cause the root context to be canceled, and trigger the normal logic in `subworkflow.go` that yields cancellation events for an active sub-workflow. 
This will also make it easier to implement #47 in the future
=> Simplify sub-workflow cancellation propagation

backend/mysql/mysql.go, backend/redis/workflow.go, backend/sqlite/sqlite.go, backend/test/e2e.go, internal/command/command.go, internal/workflow/executor.go, samples/subworkflow/subworkflow.go, workflow/subworkflow.go, workflow/timer.go
The way sub-workflow cancellation works is like this:
When you cancel a “parent” workflow via the client, for example, what happens is that a `WorkflowExecutionCanceled` (https://github.com/cschleiden/go-workflows/blob/a20bbf5807d7cfe99d9e5073507de75ff7c49876/internal/history/history.go#L18) event is added to the parent workflows “pending events”, and that workflow is put on the workflow task queue. This will cause the executor to run that workflow, replay the history up to that point, and then execute that `WorkflowExecutionCanceled` event. As a result of that, the root `workflow.Context` that’s passed into the workflow is canceled. 
If the parent workflow has spawned any sub-workflows at that time, this handler that was added to the context is being called: …
=> Fix timer/sub-workflow cancellation before the command is committed 

workflow/sideeffect.go
Right now to use `SideEffect` you need to pass in an anonymous func that takes a `sync.Context`. However, code outside this repo can't reference `sync` since it's an internal package.
=> make `SideEffect` usable outside of repo

README.md
👋 A tiny documentation fix, I believe this argument was missed in some example code.
=> Tiny doc fix

backend/redis/events.go, backend/redis/instance.go, backend/redis/keys.go, backend/redis/queue.go, backend/redis/queue_test.go, backend/redis/signal.go, backend/redis/workflow.go, internal/workflow/executor.go
The Redis backend ignored the `lastSequenceID` and always returned the full history. The executor though, assumed that it only received events with sequence id `>=` the given `lastSequenceID` and tried to replay all the received events on its own state. This led to some events being executed twice. Depending on the workflow this was caught or not.
With this change, the redis backend uses sequence IDs as the message ids for the history stream and a direct `XRANGE` query to retrieve events with sequence id >= a given `lastSequenceID`.
=> Honor `lastSequenceID` parameter when retrieving history from redis backend

.github/workflows/go.yml, backend/mysql/mysql.go, backend/redis/workflow.go, backend/sqlite/sqlite.go, backend/test/e2e.go, internal/command/cancel_subworkflow.go, internal/command/cancel_timer.go, internal/command/command.go, internal/command/schedule_subworkflow.go, internal/command/sideeffect.go, internal/history/grouping.go, internal/history/grouping_test.go, internal/workflow/executor.go, workflow/activity.go, workflow/subworkflow.go, workflow/timer.go
When executing workflow instances without cached executor instances, during replay some commands weren't put into the correct state. This lead to required events not being generated. Most notably, scheduled future events for cancelled timers were not cleaned up. This could lead to events being delivered to an already completed workflow instance, which leads to errors when trying to process those.
This also raised some gaps in the testing. With this change all e2e tests are run twice, with executor instance caching and without. This increases the time for running all tests quite a bit, but the increased coverage is worth it.
=> Fix uncached command handling

internal/workflow/executor_test.go, workflow/retries.go, workflow/subworkflow.go
Closes #119 
Supports #121
This also helps with a "race condition" when writing workflows. From my notes:
- There is race condition, where sending a signal to a workflow instance that doesn't yet exist can lead to an issue. It's easy to hit with code like this:  
``` go
func Workflow(ctx workflow.Context) error {
subWorkflowInstanceID := "..."
// (1)
f := workflow.CreateSubWorkflowInstance(ctx, ..., SubWorkflow)
// (2)
workflow.SignalWorkflow(ctx, subWorkflowInstanceID, "signal", "value")  
result, err := f.Get(ctx)
}
```
(1) is implemented via `withRetry` by default, which uses a Coroutine to schedule the sub-workflow. Since there is no `Yield` before (2), the `SignalWorkflow` command is created *before* the `CreateSubWorkflowInstance` command. `SignalWorkflow` just delivers an event to …
=> Adjust sub-workflow retry behavior

README.md, internal/sync/channel.go, internal/sync/selector.go, internal/sync/selector_test.go, workflow/sync.go
This adds a `Send` case to the `Select` function, similar to:
```go
var c chan int
select {
case c <- 42:
// Value was sent 
}
```
=> Add Send case to the Select function

.github/workflows/go.yml, backend/test/e2e.go, client/client.go
Primary motivation at this point is to reduce the time it takes to run the tests. With this the Redis integration tests go from 40s to 3s, same for SQLite. 
MySQL is faster, but still suffers from the `CREATE/DROP` DB setup/teardown.
=> Use exponential backoff when waiting for workflow results

backend/backend.go, backend/mock_Backend.go, backend/mysql/diagnostics.go, backend/mysql/mysql.go, backend/redis/instance.go, backend/redis/workflow.go, backend/sqlite/diagnostics.go, backend/sqlite/sqlite.go, backend/test/backendtest.go, backend/test/e2e.go, client/client.go, client/client_test.go, diag/backend.go, go.mod, internal/core/state.go, internal/task/workflow.go, internal/worker/activity.go, internal/worker/workflow.go, internal/workflow/executor.go
Instead of `panic`ing when dequeuing a workflow task with new events for an already completed instance, this will instead log the events and discard them. 
There are valid scenarios where events might get delivered to an already completed instance, like workflow instances sending events to each other. We cannot fail in this case, and the destination instance might already be completed when the source instance completes its workflow task.
In the future we might want to wake up the instance again or have other behavior to handle those kinds of signals, for now we assume that those signals aren't important.
=> Discard events for completed workflow instances

internal/workflow/executor.go, internal/workflow/executor_test.go
This PR modifies  the `executor` to be aware of whether or not it has seen a `WorkflowExecutionStarted` event while executing tasks for the workflow instance it is associated with. 
```diff
type executor struct {
+ wfStartedEventSeen bool
}
```
If it has seen this event previously, execution continues as normal. If it _hasn't_ seen the event previously, it checks through the events in the current task prior to executing any of them. If one of those events is `WorkflowExecutionStarted`, it shifts that event to the front of `t.NewEvents`, ensuring that `WorkflowExecutionStarted` is processed immediately after the `WorkflowTaskStarted` event. This in turn ensures that the `Scheduler` the workflow struct contains is never `nil`, preventing the `nil` pointer dereference error described in …
=> Fix out of order events bug + add test

backend/sqlite/sqlite.go
There appears to be a typo in the return type of `NewSqliteBackend` which produces this compiler error when trying to use it
```
orch/orch.go:123:12: cannot use b (variable of type backend.Backend) as type diag.Backend in struct literal:
backend.Backend does not implement diag.Backend (missing GetWorkflowInstance method)
```
=> Fixed return type of NewSqliteBackend

tester/tester.go
When unit testing workflows, ensure activities are scheduled after processing other workflow events.
=> Schedule activities last when unit testing

tester/tester.go, tester/tester_timers_test.go
This change modifies the tester to not run scheduled callbacks/timers while activities are running. 
This does not yet address cases where there is a legitimate race between an activity and a timer, this will be done in a followup PR.
=> Do not run tester timers while activities are running

tester/tester.go
Makes the error message when registering the workflow under test in `tester.go` a tad bit clearer
=> Make error message clearer

tester/options.go, tester/tester.go, tester/tester_activity_test.go, tester/tester_logger_test.go, tester/tester_timer.go, tester/tester_timers_test.go
Use a more explicit mode and switch between the two different ways of updating time during workflow test runs.
=> Explicitly switch between timer modes in test

internal/command/cancelablecommand.go, internal/command/command.go, internal/command/sideeffect.go, internal/sync/channel.go, internal/sync/channel_test.go, workflow/subworkflow.go, workflow/timer.go, workflow/timer_test.go
Changes:
- `func`s in Go cannot be compared, so change `Channel` to accept `struct`s for cancellation callbacks
- Add option to remove cancellation callbacks
- When a Timer or SubWorkflow command is finished, remove the cancellation callback to prevent invalid state transitions.
Fixes: https://github.com/cschleiden/go-workflows/issues/160
=> Support invalid state transition for finished commands during workflow cancellation 

README.md, backend/backend.go, backend/mock_Backend.go, backend/mysql/mysql.go, backend/redis/delete.go, backend/redis/instance.go, backend/redis/keys.go, backend/redis/redis.go, backend/sqlite/sqlite.go, backend/test/backendtest.go, backend/test/e2e.go, client/client.go
Contributes to #28 
Not yet an automated or time based cleanup, but a way to explicitly remove finished workflow instances.
=> Support removing workflow instances

README.md, backend/redis/expire.go, backend/redis/expire_test.go, backend/redis/keys.go, backend/redis/options.go, backend/redis/redis.go, backend/redis/redis_test.go, backend/redis/workflow.go
Allows setting an automatic expiration for finished workflows in the Redis backend. See the `README.md` for how to use and the integration test included here. 
Closes: #45
=> Automatic expiration of finished workflow instances 

analyzer/analyzer.go, analyzer/analyzer_test.go, analyzer/plugin/plugin.go, analyzer/testdata/src/p/p.go, analyzer/testdata/src/q/q1.go, analyzer/testdata/src/q/q2.go
- Handle multiple files in the analyzer
- Pre-filter AST nodes for better performance
- By default does not check private (not exported) workflows in a file. Can be overridden via the `checkprivatereturnvalues` flag. Unfortunately golangci-lint doesn't yet support passing configuration to custom linters so you'll have to update/copy  `plugin/plugin.go` for now.
=> Make analyzer work for multiple files

README.md
ContinueAsNew is supported, remove the passage from the readme saying it's not.
=> Update docs: ContinueAsNew is supported

internal/workflow/executor.go
https://github.com/cschleiden/go-workflows/pull/220 
In that PR we are passing  a single argument to the function, which is a slice. In this case, the function receives a slice of `interface{} ([]interface{})` where the only element is another slice of `interface{}`.
To retain existing behavior, using `...`
=> Fix: flatten logging fields regression

internal/worker/activity.go
Something I noticed while running this with our workloads, we probably don't want to silently ignore errors that are not `DeadlineExceeded`.
=> do not silently ignore errors in ActivityWorker.poll

bench/main.go
The new polling interval introduces much deviation in the tests, making them unnecessarily slow. This should help to visualize better the performance of each individual backend.
=> uses monoprocess backend for bench

backend/sqlite/activities.go, backend/sqlite/db/migrations/000002_add_attributes_table.down.sql, backend/sqlite/db/migrations/000002_add_attributes_table.up.sql, backend/sqlite/events.go, backend/sqlite/sqlite.go
This change adds a new `attributes` table to the sqlite backend. Serialized attributes for events are stored in that table instead of inline. 
Contributes to: #39
=> Sqlite: store payloads/attributes in separate table

backend/mysql/db/migrations/000003_add_attributes_table.down.sql, backend/mysql/db/migrations/000003_add_attributes_table.up.sql, backend/mysql/events.go, backend/mysql/mysql.go, backend/mysql/mysql_test.go, backend/sqlite/db/migrations/000002_add_attributes_table.down.sql, backend/sqlite/db/migrations/000002_add_attributes_table.up.sql
=> Move mysql attributes to separate table

backend/redis/delete.go, backend/redis/expire.go
Missed this when moving event payloads to a separate key.
=> Delete and expire event payloads

backend/redis/diagnostics_test.go, backend/redis/instance.go, backend/redis/keys.go, backend/redis/scripts/complete_workflow_task.lua, backend/redis/scripts/create_workflow_instance.lua, backend/redis/workflow.go
=> Track newly created instances correctly

internal/workflow/executor.go, internal/workflow/executor_test.go, internal/workflowstate/workflowstate.go, internal/workflowstate/workflowstate_test.go, workflow/activity.go, workflow/sideeffect.go, workflow/subworkflow.go, workflow/timer.go, workflow/timer_test.go
With this change, pending futures are tracked with a name. When a workflow exits with pending futures, the names will be included in the log and the `panic`. For complicated workflows, this should make it clearer which futures are still pending. 
With two pending workflows, the error could look like this:
```
workflow completed, but there are still pending futures: [1-subworkflow:1 2-timer:2s]
```
=> Track pending futures with a name

internal/sync/coroutine.go, internal/sync/coroutine_test.go, internal/workflow/executor_test.go
Ensure coroutines exit cleanly and don't try to block before.
=> Ensure coroutines exit cleanly

.vscode/settings.json
This is a small QoL improvement for redis script static diagnostics, helping to remove noise when using the lua language server vscode extension.
* define redis script globals in lua language server vscode settings
=> define redis globals for vscode lua language server diagnostics

internal/sync/waitgroup.go, internal/sync/waitgroup_test.go
When `Wait`-ing on the wait group after the wait counter was set to `0` already, the `Wait` would never return
=> Fix waitgroup when waiting after Done

tester/tester.go
Allow access to the activity mock when testing workflows. Without this it's not possible to check that a certain activity has not been called.
=> Allow access to activity mock

tester/tester.go, tester/tester_subworkflow_test.go, tester/tester_test.go
This allows testing of canceled workflow contexts, and seemed to be needed.  Please correct me if I'm wrong.
=> feat(tester): cancel workflow instance

tester/options.go, tester/tester.go, tester/tester_test.go
This PR resolves #370.
This option sets the initial mocked time for a workflow tester to enable testing date- and/or time-of-day-dependent behavior.
=> feat(tester): add WithInitialTime option

backend/metrics/metrics.go, backend/options.go, backend/test/e2e.go, internal/worker/workflow.go, tester/options.go, tester/tester.go, workflow/executor/cache/cache_test.go, workflow/executor/executor.go, workflow/executor/executor_test.go
Add a hard-limit for workflow history sizes. Defaults to 10k events. 
Closes: https://github.com/cschleiden/go-workflows/issues/207
=> Support max history size

.github/workflows/bench.yml
This pull request refactors the `.github/workflows/bench.yml` workflow to split benchmark jobs by backend (MySQL, SQLite, Redis), improve modularity, and enhance artifact handling and result reporting. Each backend now runs in its own job, with results uploaded and then combined for a final benchmark summary comment. The workflow also updates some dependencies and conditions for greater flexibility.
=> Split benchmark jobs

workflow/activity.go, workflow/activity_test.go
Allow for activity to be executed via their registered name.
Fixes #378
=> Execute activity with name

samples/activity-registration/activity-registration.go, samples/cancellation/cancellation.go, samples/complex-parameters/complex-parameters.go, samples/concurrent/concurrent.go, samples/context-propagation/context_propagation.go, samples/continue-as-new/continue-as-new.go, samples/converter/converter.go, samples/errors/errors.go, samples/orchestrator/main.go, samples/queues/queues.go, samples/retries/retries.go, samples/runner.go, samples/scale/starter/main.go, samples/scale/worker/main.go, samples/signal-subworkflow/subworkflow-signal.go, samples/signal/signal.go, samples/simple-split-worker/starter/main.go, samples/simple-split-worker/worker/main.go, samples/simple/simple.go, samples/subworkflow/subworkflow.go, samples/timer/timer.go, samples/tracing/tracing.go, samples/web/web.go, samples/workflow-registration/workflow_registration.go
Only clear the backend state (Flush for Redis) for samples that do not have a split worker and starter.
=> Update GetBackend calls to include clear option for backend initialization
